title: Portfolio of Simen Wolters

logo: /assets/images/profile.jpg

baseurl: ""
url: ""

social:
  github: "https://github.com/SimenWol"
  linkedin: "https://www.linkedin.com/in/simenwolters/"
  itchio: "https://simenwolters.itch.io/"
  youtube: "https://www.youtube.com/@simenwolters"
  gmail: "simenwol@gmail.com"
  resume: /assets/Resume_Simen_Wolters.pdf

name: Simen Wolters
profession: Generalist Game Programmer

collections:
  projects:
    output: true
    permalink: /projects/:name/

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed